package com.flaviocecca.ondalunga.game

data class Spectrum(val left: String, val right: String)

object Spectra {
    val all: List<Spectrum> = listOf(
        Spectrum("Freddo", "Caldo"),
        Spectrum("Sottovalutato", "Sopravvalutato"),
        Spectrum("Inutile", "Indispensabile"),
        Spectrum("Da evitare al primo appuntamento", "Perfetto al primo appuntamento"),
        Spectrum("Cibo triste", "Cibo che consola"),
        Spectrum("Noioso", "Emozionante"),
        Spectrum("Facile da imparare", "Difficile da imparare"),
        Spectrum("Brutto regalo", "Regalo perfetto"),
        Spectrum("Profuma", "Puzza"),
        Spectrum("Passato di moda", "Di tendenza"),
        Spectrum("Lo fanno in pochi", "Lo fanno tutti"),
        Spectrum("Rilassante", "Stressante"),
        Spectrum("Da bambini", "Da adulti"),
        Spectrum("Economico", "Costoso"),
        Spectrum("Silenzioso", "Rumoroso"),
        Spectrum("Sano", "Fa malissimo"),
        Spectrum("Fa paura", "Fa tenerezza"),
        Spectrum("Pessimo superpotere", "Superpotere fantastico"),
        Spectrum("Film dimenticabile", "Capolavoro"),
        Spectrum("Mestiere tranquillo", "Mestiere pericoloso"),
        Spectrum("Si mangia a colazione", "Si mangia a cena"),
        Spectrum("Poco italiano", "Italianissimo"),
        Spectrum("Animale antipatico", "Animale adorabile"),
        Spectrum("Abitudine innocua", "Abitudine insopportabile"),
        Spectrum("Lento", "Veloce"),
        Spectrum("Morbido", "Duro"),
        Spectrum("Dolce", "Salato"),
        Spectrum("Sport per pigri", "Sport massacrante"),
        Spectrum("Da soli", "In compagnia"),
        Spectrum("Vacanza da incubo", "Vacanza da sogno"),
        Spectrum("Invenzione trascurabile", "Invenzione che ha cambiato il mondo"),
        Spectrum("Si perdona", "Imperdonabile"),
        Spectrum("Elegante", "Trasandato"),
        Spectrum("Personaggio buono", "Personaggio cattivo"),
        Spectrum("Scusa credibile", "Scusa ridicola"),
        Spectrum("Materia facile", "Materia impossibile"),
        Spectrum("Canzone triste", "Canzone allegra"),
        Spectrum("Si usa una volta l'anno", "Si usa ogni giorno"),
        Spectrum("Piccolo", "Enorme"),
        Spectrum("Naturale", "Artificiale"),
        Spectrum("Pulito", "Sporco"),
        Spectrum("Mette ansia", "Mette pace"),
        Spectrum("Da mattinieri", "Da nottambuli"),
        Spectrum("Lavoro mal pagato", "Lavoro strapagato"),
        Spectrum("Piace ai nonni", "Piace ai ragazzi"),
        Spectrum("Sulla pizza no", "Sulla pizza sì"),
        Spectrum("Fragile", "Indistruttibile"),
        Spectrum("Ordinario", "Stravagante"),
        Spectrum("Serve in città", "Serve in campagna"),
        Spectrum("Segreto da poco", "Segreto inconfessabile"),
        Spectrum("Poco romantico", "Romanticissimo"),
        Spectrum("Si impara a scuola", "Si impara dalla vita"),
        Spectrum("Liscio", "Ruvido"),
        Spectrum("Nome da cane", "Nome da gatto"),
        Spectrum("Dura un attimo", "Dura per sempre"),
        Spectrum("Mai visto", "Visto e stravisto"),
        Spectrum("Ti fa dormire", "Ti tiene sveglio"),
        Spectrum("Fuori posto a un matrimonio", "Immancabile a un matrimonio"),
        Spectrum("Poco fotogenico", "Da cartolina"),
        Spectrum("Leggero", "Pesante"),
        Spectrum("Peccato veniale", "Peccato mortale"),
        Spectrum("Da intenditori", "Per tutti"),
        Spectrum("Poco utile su un'isola deserta", "Vitale su un'isola deserta"),
        Spectrum("Invernale", "Estivo"),
        Spectrum("Sa di poco", "Saporitissimo"),
        Spectrum("Meglio dal vivo", "Meglio in TV"),
        Spectrum("Richiede fortuna", "Richiede bravura"),
        Spectrum("Sembra facile", "Sembra difficile"),
        Spectrum("Nessuno lo ammette", "Tutti se ne vantano"),
        Spectrum("Antico", "Futuristico"),
        Spectrum("Cattivo coinquilino", "Coinquilino ideale"),
        Spectrum("Timido", "Sfacciato"),
        Spectrum("Rotondo", "Spigoloso"),
        Spectrum("Lo compri d'impulso", "Ci pensi per mesi"),
        Spectrum("Giorno feriale", "Giorno di festa"),
        Spectrum("Asciutto", "Bagnato"),
        Spectrum("Si mangia con le mani", "Si mangia con le posate"),
        Spectrum("Buia", "Luminosa"),
        Spectrum("Argomento sicuro a tavola", "Argomento da lite a tavola"),
        Spectrum("Poco contagioso", "Contagiosissimo"),
        Spectrum("Colazione da hotel triste", "Colazione da re"),
        Spectrum("Gusto di gelato da evitare", "Gusto di gelato perfetto"),
        Spectrum("Si mangia freddo", "Si mangia bollente"),
        Spectrum("Piatto da tutti i giorni", "Piatto delle feste"),
        Spectrum("Cibo da stadio", "Cibo da ristorante stellato"),
        Spectrum("Pessimo ripieno per un panino", "Ripieno perfetto per un panino"),
        Spectrum("Bevanda da bambini", "Bevanda da adulti"),
        Spectrum("Croccante", "Molliccio"),
        Spectrum("Si cucina in cinque minuti", "Si cucina in cinque ore"),
        Spectrum("Poco piccante", "Piccantissimo"),
        Spectrum("Spuntino di mezzanotte sbagliato", "Spuntino di mezzanotte ideale"),
        Spectrum("Verdura odiata", "Verdura amata"),
        Spectrum("Nord Italia", "Sud Italia"),
        Spectrum("Tradizione di famiglia", "Moda del momento"),
        Spectrum("Da bar di paese", "Da locale alla moda"),
        Spectrum("Gesto poco italiano", "Gesto italianissimo"),
        Spectrum("Film da guardare da soli", "Film da guardare in gruppo"),
        Spectrum("Fa ridere", "Fa piangere"),
        Spectrum("Serie da abbandonare", "Serie da divorare"),
        Spectrum("Finale deludente", "Finale perfetto"),
        Spectrum("Cartone dimenticato", "Cartone leggendario"),
        Spectrum("Cantante stonato", "Voce incredibile"),
        Spectrum("Canzone da doccia", "Canzone da stadio"),
        Spectrum("Supereroe scarso", "Supereroe imbattibile"),
        Spectrum("Cattivo ridicolo", "Cattivo terrificante"),
        Spectrum("Gioco da tavolo noioso", "Gioco da tavolo che rovina amicizie"),
        Spectrum("Videogioco rilassante", "Videogioco che fa infuriare"),
        Spectrum("Libro da spiaggia", "Libro da università"),
        Spectrum("Personaggio famoso simpatico", "Personaggio famoso antipatico"),
        Spectrum("Realistico", "Fantascienza pura"),
        Spectrum("Sport noioso da guardare", "Sport spettacolare da guardare"),
        Spectrum("Hobby economico", "Hobby che ti manda in rovina"),
        Spectrum("Si fa al chiuso", "Si fa all'aperto"),
        Spectrum("Richiede forza", "Richiede cervello"),
        Spectrum("Passatempo da nonni", "Passatempo da ragazzini"),
        Spectrum("Attività da domenica mattina", "Attività da sabato sera"),
        Spectrum("Animale stupido", "Animale geniale"),
        Spectrum("Animale innocuo", "Animale letale"),
        Spectrum("Pessimo animale domestico", "Animale domestico perfetto"),
        Spectrum("Fa schifo", "Fa gola"),
        Spectrum("Vive pochissimo", "Vive tantissimo"),
        Spectrum("Peloso", "Liscio come un sasso"),
        Spectrum("Meta per riposare", "Meta per l'avventura"),
        Spectrum("Città sopravvalutata", "Città da vedere almeno una volta"),
        Spectrum("Vicino a casa", "In capo al mondo"),
        Spectrum("Inutile in valigia", "Indispensabile in valigia"),
        Spectrum("Mezzo di trasporto scomodo", "Mezzo di trasporto comodissimo"),
        Spectrum("Posto deserto", "Posto affollatissimo"),
        Spectrum("Da turisti", "Da gente del posto"),
        Spectrum("Montagna", "Mare"),
        Spectrum("Lavoro che nessuno sogna", "Lavoro dei sogni"),
        Spectrum("Lavoro manuale", "Lavoro da scrivania"),
        Spectrum("Mestiere in via d'estinzione", "Mestiere del futuro"),
        Spectrum("Riunione inutile", "Riunione necessaria"),
        Spectrum("Pessimo capo", "Capo ideale"),
        Spectrum("Materia inutile nella vita", "Materia utilissima nella vita"),
        Spectrum("Scusa per i compiti credibile", "Scusa per i compiti assurda"),
        Spectrum("Si dimentica subito", "Non si scorda mai"),
        Spectrum("Oggetto da buttare", "Oggetto da tenere per sempre"),
        Spectrum("Tecnologia superata", "Tecnologia all'avanguardia"),
        Spectrum("App inutile", "App di cui non puoi fare a meno"),
        Spectrum("Si rompe subito", "Dura una vita"),
        Spectrum("Sta in tasca", "Non passa dalla porta"),
        Spectrum("Acquisto intelligente", "Soldi buttati"),
        Spectrum("Da tenere in bagno", "Da tenere in cucina"),
        Spectrum("Elettrodomestico trascurabile", "Elettrodomestico salvavita"),
        Spectrum("Comodo", "Scomodissimo"),
        Spectrum("Si trova in ogni casa", "Non ce l'ha nessuno"),
        Spectrum("Di plastica", "Di lusso"),
        Spectrum("Bugia innocente", "Bugia gravissima"),
        Spectrum("Pregio", "Difetto"),
        Spectrum("Normale tra amici", "Strano tra amici"),
        Spectrum("Da dire a un colloquio", "Da non dire mai a un colloquio"),
        Spectrum("Primo messaggio pessimo", "Primo messaggio perfetto"),
        Spectrum("Motivo stupido per lasciarsi", "Motivo serio per lasciarsi"),
        Spectrum("Amico da evitare in vacanza", "Amico ideale in vacanza"),
        Spectrum("Ospite sgradito", "Ospite perfetto"),
        Spectrum("Vicino di casa da incubo", "Vicino di casa d'oro"),
        Spectrum("Si dice in faccia", "Si dice alle spalle"),
        Spectrum("Imbarazzante", "Motivo d'orgoglio"),
        Spectrum("Complimento strano", "Complimento bellissimo"),
        Spectrum("Paura sensata", "Paura assurda"),
        Spectrum("Maleducato", "Educatissimo"),
        Spectrum("Da introversi", "Da estroversi"),
        Spectrum("Fa arrabbiare poco", "Fa perdere la testa"),
        Spectrum("Pessimo nome per un figlio", "Bel nome per un figlio"),
        Spectrum("Fa passare il tempo lentamente", "Fa volare il tempo"),
        Spectrum("Faccenda di casa sopportabile", "Faccenda di casa odiosa"),
        Spectrum("Lunedì mattina", "Venerdì sera"),
        Spectrum("Si fa di nascosto", "Si fa davanti a tutti"),
        Spectrum("Abitudine da vecchi", "Abitudine da giovani"),
        Spectrum("Spreco di tempo", "Tempo ben speso"),
        Spectrum("Si rimanda sempre", "Si fa subito"),
        Spectrum("Buon proposito realistico", "Buon proposito impossibile"),
        Spectrum("Risveglio da incubo", "Risveglio perfetto"),
        Spectrum("Sfortuna da poco", "Sfortuna nera"),
        Spectrum("Regalo da riciclare", "Regalo da conservare"),
        Spectrum("Festa noiosa", "Festa memorabile"),
        Spectrum("Natale", "Ferragosto"),
        Spectrum("Pessimo costume di carnevale", "Costume di carnevale geniale"),
        Spectrum("Ballo imbarazzante", "Ballo irresistibile"),
        Spectrum("Brindisi sbagliato", "Brindisi perfetto"),
        Spectrum("Poco probabile", "Praticamente certo"),
        Spectrum("Legale", "Illegale"),
        Spectrum("Sicuro", "Rischioso"),
        Spectrum("Semplice", "Complicato"),
        Spectrum("Vero", "Leggenda metropolitana"),
        Spectrum("Banale", "Geniale"),
        Spectrum("Raro", "Comunissimo"),
        Spectrum("Pubblico", "Privato"),
        Spectrum("Serio", "Ridicolo"),
        Spectrum("Sottile", "Spesso"),
        Spectrum("Trasparente", "Misterioso"),
        Spectrum("Si compra", "Non ha prezzo"),
        Spectrum("Bello fuori", "Bello dentro"),
        Spectrum("Colore triste", "Colore allegro"),
        Spectrum("Suono fastidioso", "Suono piacevole"),
        Spectrum("Odore di casa", "Odore di ospedale"),
        Spectrum("Vicino", "Lontanissimo"),
        Spectrum("Corto", "Lunghissimo"),
        Spectrum("Appiccicoso", "Scivoloso"),
        Spectrum("Inutile in un'apocalisse zombie", "Vitale in un'apocalisse zombie"),
        Spectrum("Pessimo da trovare nel letto", "Bello da trovare nel letto"),
        Spectrum("Desiderio al genio sprecato", "Desiderio al genio azzeccato"),
        Spectrum("Inutile nello spazio", "Fondamentale nello spazio"),
        Spectrum("Pessimo presidente", "Ottimo presidente"),
        Spectrum("Epoca in cui non vorresti vivere", "Epoca in cui vorresti vivere"),
        Spectrum("Tatuaggio di cui pentirsi", "Tatuaggio di cui andare fieri"),
        Spectrum("Utile in una rapina", "D'intralcio in una rapina"),
        Spectrum("Ultima cena deludente", "Ultima cena perfetta"),
        Spectrum("Pessimo nome per una band", "Gran nome per una band"),
        Spectrum("Si sopravvive facilmente", "Non se ne esce vivi"),
        Spectrum("Peggior modo di diventare famosi", "Miglior modo di diventare famosi"),
        Spectrum("Vale poco al mercatino", "Vale una fortuna al mercatino"),
        Spectrum("Mostro da coccolare", "Mostro da incubo"),
        Spectrum("Pianeta inospitale", "Pianeta da colonizzare"),
        Spectrum("Moda da dimenticare", "Moda da riportare in auge"),
        Spectrum("Capo d'abbigliamento comodo", "Capo d'abbigliamento da tortura"),
        Spectrum("Pettinatura sobria", "Pettinatura esagerata"),
        Spectrum("Outfit da divano", "Outfit da gala"),
        Spectrum("Profumo discreto", "Profumo che stordisce"),
    )
}
