package com.flaviocecca.ondalunga.game

data class Spectrum(val left: String, val right: String)

object Spectra {
    val all: List<Spectrum> = listOf(
        Spectrum("Freddo", "Caldo"),
        Spectrum("Sottovalutato", "Sopravvalutato"),
        Spectrum("Inutile", "Indispensabile"),
        Spectrum("Da evitare al primo appuntamento", "Perfetto al primo appuntamento"),
        Spectrum("Cibo triste", "Cibo che consola"),
        Spectrum("Noioso", "Emozionante"),
        Spectrum("Facile da imparare", "Difficile da imparare"),
        Spectrum("Brutto regalo", "Regalo perfetto"),
        Spectrum("Profuma", "Puzza"),
        Spectrum("Passato di moda", "Di tendenza"),
        Spectrum("Lo fanno in pochi", "Lo fanno tutti"),
        Spectrum("Rilassante", "Stressante"),
        Spectrum("Da bambini", "Da adulti"),
        Spectrum("Economico", "Costoso"),
        Spectrum("Silenzioso", "Rumoroso"),
        Spectrum("Sano", "Fa malissimo"),
        Spectrum("Fa paura", "Fa tenerezza"),
        Spectrum("Pessimo superpotere", "Superpotere fantastico"),
        Spectrum("Film dimenticabile", "Capolavoro"),
        Spectrum("Mestiere tranquillo", "Mestiere pericoloso"),
        Spectrum("Si mangia a colazione", "Si mangia a cena"),
        Spectrum("Poco italiano", "Italianissimo"),
        Spectrum("Animale antipatico", "Animale adorabile"),
        Spectrum("Abitudine innocua", "Abitudine insopportabile"),
        Spectrum("Lento", "Veloce"),
        Spectrum("Morbido", "Duro"),
        Spectrum("Dolce", "Salato"),
        Spectrum("Sport per pigri", "Sport massacrante"),
        Spectrum("Da soli", "In compagnia"),
        Spectrum("Vacanza da incubo", "Vacanza da sogno"),
        Spectrum("Invenzione trascurabile", "Invenzione che ha cambiato il mondo"),
        Spectrum("Si perdona", "Imperdonabile"),
        Spectrum("Elegante", "Trasandato"),
        Spectrum("Personaggio buono", "Personaggio cattivo"),
        Spectrum("Scusa credibile", "Scusa ridicola"),
        Spectrum("Materia facile", "Materia impossibile"),
        Spectrum("Canzone triste", "Canzone allegra"),
        Spectrum("Si usa una volta l'anno", "Si usa ogni giorno"),
        Spectrum("Piccolo", "Enorme"),
        Spectrum("Naturale", "Artificiale"),
        Spectrum("Pulito", "Sporco"),
        Spectrum("Mette ansia", "Mette pace"),
        Spectrum("Da mattinieri", "Da nottambuli"),
        Spectrum("Lavoro mal pagato", "Lavoro strapagato"),
        Spectrum("Piace ai nonni", "Piace ai ragazzi"),
        Spectrum("Sulla pizza no", "Sulla pizza sì"),
        Spectrum("Fragile", "Indistruttibile"),
        Spectrum("Ordinario", "Stravagante"),
        Spectrum("Serve in città", "Serve in campagna"),
        Spectrum("Segreto da poco", "Segreto inconfessabile"),
        Spectrum("Poco romantico", "Romanticissimo"),
        Spectrum("Si impara a scuola", "Si impara dalla vita"),
        Spectrum("Liscio", "Ruvido"),
        Spectrum("Nome da cane", "Nome da gatto"),
        Spectrum("Dura un attimo", "Dura per sempre"),
        Spectrum("Mai visto", "Visto e stravisto"),
        Spectrum("Ti fa dormire", "Ti tiene sveglio"),
        Spectrum("Fuori posto a un matrimonio", "Immancabile a un matrimonio"),
        Spectrum("Poco fotogenico", "Da cartolina"),
        Spectrum("Leggero", "Pesante"),
        Spectrum("Peccato veniale", "Peccato mortale"),
        Spectrum("Da intenditori", "Per tutti"),
        Spectrum("Poco utile su un'isola deserta", "Vitale su un'isola deserta"),
        Spectrum("Invernale", "Estivo"),
        Spectrum("Sa di poco", "Saporitissimo"),
        Spectrum("Meglio dal vivo", "Meglio in TV"),
        Spectrum("Richiede fortuna", "Richiede bravura"),
        Spectrum("Sembra facile", "Sembra difficile"),
        Spectrum("Nessuno lo ammette", "Tutti se ne vantano"),
        Spectrum("Antico", "Futuristico"),
        Spectrum("Cattivo coinquilino", "Coinquilino ideale"),
        Spectrum("Timido", "Sfacciato"),
        Spectrum("Rotondo", "Spigoloso"),
        Spectrum("Lo compri d'impulso", "Ci pensi per mesi"),
        Spectrum("Giorno feriale", "Giorno di festa"),
        Spectrum("Asciutto", "Bagnato"),
        Spectrum("Si mangia con le mani", "Si mangia con le posate"),
        Spectrum("Buia", "Luminosa"),
        Spectrum("Argomento sicuro a tavola", "Argomento da lite a tavola"),
        Spectrum("Poco contagioso", "Contagiosissimo"),
    )
}
